name: .NET CI - Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@692973e3d937129bcbf406c05a286dbbcec772e3 # v4.1.7

    - name: Configurar .NET 10
      uses: actions/setup-dotnet@6db8373b502f2e497c3011db657a824eccd5d60e # v4.0.1
      with:
        dotnet-version: '10.0.x'

    - name: Restaurar dependencias
      run: dotnet restore Gamification.slnx

    - name: Compilar (Build)
      run: dotnet build Gamification.slnx --no-restore --configuration Release

    - name: Ejecutar Pruebas (Test)
      run: dotnet test Gamification.slnx --no-build --verbosity normal --configuration Release
