name: Build and deploy ASP.Net Core app to Azure Web App - gamification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore
        run: dotnet restore src/Gamification.Api/Gamification.Api.csproj

      - name: Build
        run: dotnet build src/Gamification.Api/Gamification.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/Gamification.Api/Gamification.Api.csproj --configuration Release --no-build --output ${{ env.DOTNET_ROOT }}/myapp

      - uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: .net-app

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6A3BCFBE67784D2D995886F9127386CA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DC80AA9A3DD7456B894A77CAFB28EABF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F655F7782CD0481B9C0B950F6B9C8714 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: gamification
          slot-name: Production
          package: .
